-- Collapse the cleaning workflow: dirty rooms are now marked
-- 'available' in one step. The intermediate 'clean' and 'inspected'
-- statuses go away.
--
-- 1. Backfill: any room currently sitting in clean/inspected becomes
--    available. (Audit showed 0 affected rows at migration time, but
--    the UPDATE is idempotent and safe to re-run.)
-- 2. Drop the CHECK constraint that pinned status to the old enum,
--    re-create it without clean/inspected. Drizzle doesn't manage
--    Postgres CHECK constraints automatically, so we do it here.
--
-- The rooms.status column stays TEXT (no native ENUM type was used).

UPDATE rooms
SET status = 'available', updated_at = NOW()
WHERE status IN ('clean', 'inspected');

-- Find and drop the existing CHECK constraint on rooms.status. The
-- constraint name is auto-generated by Postgres ('rooms_status_check'
-- in the baseline), but we look it up dynamically so this migration
-- survives renames.
DO $$
DECLARE
  con_name TEXT;
BEGIN
  SELECT conname INTO con_name
  FROM pg_constraint c
  JOIN pg_class t ON t.oid = c.conrelid
  WHERE t.relname = 'rooms'
    AND c.contype = 'c'
    AND pg_get_constraintdef(c.oid) ILIKE '%status%clean%';
  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE rooms DROP CONSTRAINT %I', con_name);
  END IF;
END$$;

ALTER TABLE rooms
  ADD CONSTRAINT rooms_status_check
  CHECK (status IN ('available', 'occupied', 'reserved', 'dirty', 'maintenance'));
